
spring:
  application:
    name: CONFIG-DEV

eureka:
   instance:
    prefer-ip-address: true
   client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka
